version: '1.0'
services:
  frontend:
    image: paperless:nginx
    build:
      dockerfile: frontend/Dockerfile
    ports:
      - "8080:80"
  backend:
    image: paperless:openjdk
    build:
      dockerfile: backend/Dockerfile
    ports:
      - "8088:8080"