version: '1.0'
services:
  frontend:
    image: paperless:nginx
    build:
      dockerfile: frontend/Dockerfile
    ports:
      - "8080:80"
  backend:
    image: paperless:openjdk
    build:
      dockerfile: backend/Dockerfile
    ports:
      - "8088:8080"
    depends_on:
      database:
        condition: service_healthy
      minio:
        condition: service_started
      rabbitmq:
        condition: service_started
  ocr:
    image: ocr:openjdk
    build:
      dockerfile: paperlessOCR/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      database:
        condition: service_healthy
      minio:
        condition: service_started
      rabbitmq:
        condition: service_started
      backend:
        condition: service_started
      elasticsearch:
        condition: service_started
  database:
    image: postgres:15.4
    container_name: paperless-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=paperless
      - POSTGRES_PASSWORD=paperless
      - POSTGRES_DB=paperless
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "paperless" ]
      interval: 10s
      timeout: 5s
      retries: 20
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: paperless-rabbitmq
    ports:
      - "5672:5672" # RabbitMQ main port
      - "15672:15672" # RabbitMQ management plugin port
    environment:
      RABBITMQ_DEFAULT_USER: "paperless"
      RABBITMQ_DEFAULT_PASS: "paperless"
    volumes:
      - ./rabbitmqData:/var/lib/rabbitmq
  minio:
    image: minio/minio
    container_name: paperless-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: paperless
      MINIO_ROOT_PASSWORD: paperless
      MINIO_CONSOLE_ADDRESS: :9001
    volumes:
      - ./minioData/data:/data
      - ./minioData/config:/root/.minio
    command: server /data
  elasticsearch:
    image: elasticsearch:8.7.1
    container_name: paperless-elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
      - "xpack.security.enrollment.enabled=false"
      - ELASTIC_PASSWORD=paperless
    ports:
      - 9200:9200
      - 9300:9300